### ISSUE TITLE
ActionTestFailureSummary's lineNumber can be nil

### ISSUE THREAD

**Issue by DevilDimon** [davidahouse/XCResultKit#26]
Our test runs sometimes produce XCResult bundles with ActionTestFailureSummary's `lineNumber` property not present in the dictionary, usually due to a low-level crash. We are using Xcode 11.3.1, so the schema must have silently been changed by Apple at some point. Please patch the library to allow for missing line numbers in test failure summaries.

**Comment by davidahouse** [comment]
@DevilDimon Hmmm, looking at the implementation, `lineNumber` is already an optional as far as the json parsing goes:

```
lineNumber = xcOptional(element: "lineNumber", from: json) ?? 0
```

So the default lineNumber is 0. Honestly I think a `Int?` would be a more correct datatype here, so we can consider changing it. It would be a breaking change for any libraries using that field, however. Let me think on this a bit, but just wanted to make sure there wasn't some other issue going on in your case. It should be showing `lineNumber` as 0 for the cases you mention above.

**Comment by davidahouse** [comment]
@DevilDimon Were you ever able to find more details about a crash from a missing `lineNumber`? Perhaps you were using a previous version, but the latest version should be able to handle that situation fine, returning 0 for the line number.

**Comment by DevilDimon** [comment]
Yes, I was indeed using a previous version. The `lineNumber` property appears to work correctly after updating.

**Comment by davidahouse** [comment]
@DevilDimon thank you for confirming. 👍
