### ISSUE TITLE
Can `ActionTestFailureSummary.fileName` be Optional?

### ISSUE THREAD

**Issue by AmeliaBoli** [davidahouse/XCResultKit#37]
We are having `xcresult` files with failures, but the failures are not getting parsed because the failure block does not have a `fileName`. An example of when this is happening is when "test runner exited" during SetUp.

Is there a reason that this property is required? Can we make it Optional?

I'd be happy to open a pull request. I just wanted to see if there was background information that was needed first.

**Comment by davidahouse** [comment]
I've seen a lot of cases where fields that should be present but are not. We have been changing many of these properties to Optional. I don't really have a problem with it as long as there is a case where it happens from Xcode. Bottom line is that we should be trying to parse any file from Xcode, no matter what we think should be required. :).  So yeah if you want to create a PR that works, or I'll make the change.

**Comment by AmeliaBoli** [comment]
I'm so sorry. I looks like we are pointing to an old release and it is already Optional in the latest release. I will update on our end.

**Comment by davidahouse** [comment]
Oh no worries! Glad we already fixed it. :)

What project are you using the library in? Is it something public?

**Comment by AmeliaBoli** [comment]
It is not public unfortunately. We use it in an internal tool that converts xcresult files into JUnit XML files.
