### ISSUE TITLE
Add support for Xcode 13

### ISSUE THREAD

**Issue by davidahouse** [davidahouse/XCResultKit#38]
Looks like a few new things in testing so need to run through some scenarios to ensure everything is working as expected.

**Comment by davidahouse** [comment]
Initial testing seems like everything works fine. Was able to build and run a command line app built with Xcode 13 and XCResultKit, then ran it against a test execution from Xcode 13 and it ran without crashing/errors. Will do some further research on new items added to the schema.

**Comment by tylervick** [comment]
Hey @davidahouse have you had a chance to look at any of the new items? I'm seeing an empty result from `getLogs` (besides the title).

**Comment by davidahouse** [comment]
I haven't had a chance yet. Let me grab the latest Xcode and see what's up.

**Comment by theScud** [comment]
hey @davidahouse  i can take a look for Xcode 13 and 14 , do you happen to have sample project which has a whole bunch of warnings, errors, etc ?

**Comment by davidahouse** [comment]
I usually test it on code that I happen to be also working on at the same time. But really I should create a very specific set of example apps that have warnings, errors and all kinds of tests. Feel free to create your own example in the meantime if you want to look into anything.

**Comment by davidahouse** [comment]
Closing to focus on Xcode 14 schema. See issue #41
