### ISSUE TITLE
Version 1.2.1 cannot be resolved by SPM because the tag uses an uppercase V

### ISSUE THREAD

**Issue by SSheldon** [davidahouse/XCResultKit#56]
I'm able to resolve previous versions with SPM, but not 1.2.1. The difference appears to be that previous version tags start with a lowercase v, but the 1.2.1 tag starts with an uppercase V: https://github.com/davidahouse/XCResultKit/tags

Could you please add a 1.2.1 tag with a lowercase v?

**Comment by davidahouse** [comment]
@SSheldon Sorry about that. Added the correct tag/release.
